# camera-specific parameters
STATIC_01:
  img_w: 640
  img_h: 480
  fps: 30
  camera_param: [664.8, 664.8, 320.0, 240.0, 0.000000, 2.890, 4.720, 3.390, -113.3, -27.4, 3.0]

# Temp Temp Temp
STATIC_02:
  img_w: 640
  img_h: 480
  fps: 30
  camera_param: [619.2, 619.2, 320.0, 240.0, 0.000000, 4.860, -2.520, 3.940, 151.8, -20.2, 1.0]

STATIC_03:
  img_w: 640
  img_h: 480
  fps: 30
  camera_param: [643.6, 643.6, 320.0, 240.0, 0.000000, 8.860, 3.280, 6.560, -177.6, -28.4, -3.7]

#OSRfix1_cam:
#  img_w: 640
#  img_h: 480
#  fps: 30
#  camera_param: [580.8, 580.8, 320.0, 240.0, 0.000000, -2.700, 3.520, 2.240, -33.9, -25.2, 4.7]

